apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qxzyybv6c-nodejs
  janus-idp.io/tekton: qxzyybv6c-nodejs
  backstage.io/kubernetes-id: qxzyybv6c-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qxzyybv6c-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
